### ISSUE TITLE
Example usages

### ISSUE THREAD

**Issue by RVN-BR** [cloudnautique/giddyup#2]
Hello @cloudnautique giddyup sounds like a nice project, and I have a feeling it would "bridge" some of the gaps that using rancher in production would allow...

Would you be able to give a little bit more details on what giddyup really does and some usecases?  I'm a bit confused abt the leader/follower concepts, etc, and how it "forwards" to leaders... is it some form of loadbalancing? A way of deploying services such as Rethink or Elasticsearch where multiple "nodes" work together but need one to be a "master" or leader?

Thanks for the clarification!

**Comment by cloudnautique** [comment]
Hi @RVN-BR, I have been using this for the [Galera MariaDB template](https://github.com/rancher/compose-templates/blob/master/galera/containers/0.2.0/galera-leader-proxy/run.sh). In that script, I use the forwarder to send all traffic to a single node, while running galera on the node to be a replica. The [compose file](https://github.com/rancher/compose-templates/blob/master/galera/0.2.0/docker-compose.yml) shows how the containers are pieced together in order to run. 

Ideally, this function of the leader command would move up to HA proxy and be managed by Rancher directly. The reason, the behavior is needed, is that in Galera you can only trust transaction locks if they go to a single node. So, even though its master-master setup, I want the traffic to go to one place. I am putting it behind a load balancer because we didn't want to make client changes. So VIP or client side LB within Rancher would mitigate the need for this.

The "Elect" function is used when you don't want to start the app unless it is the leader, but still want it behind a load balancer. With Galera, we needed the db up so that it was replicating between the nodes. If we didn't need that in our app, we could use "elect" and all traffic would go to the running instance of the  app on the leader. 

For Elasticsearch, and apps like it, they have their own leader election algorithms and don't need to use giddyup leader commands. The "stringify" method was created for these, because typically you need to start the servers knowing as many of the other nodes as possible. 

More of the backstory on this, when doing the app catalog templates there were common things we needed to do all the time, and this just simplifies it. You don't "Need" to install curl/jq to talk with Rancher Metadata and it saves you from having to write scripts with lots of sleeps :) (though they are still there ;) )

If you try it out, or run into issues, let me know!

**Comment by RVN-BR** [comment]
Thanks for the detailed explanation...  I'll have to look into the catalog  template a bit more and get a bit more into it to fully understand... :+1: @cloudnautique
